name: PlatformIO Build ClassicESP

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: ClassicESP
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Cache PlatformIO - ClassicESP
        uses: actions/cache@v5
        with:
          path: |
            ~/.platformio/packages
            ~/.platformio/platforms
            .ccache
          key: pio-ClassicESP-${{ hashFiles('platformio.ini') }}
          restore-keys: |
            pio-ClassicESP-

      - name: Install PlatformIO + esptool + ccache
        run: |
          sudo apt update
          sudo apt install ccache
          python -m pip install --upgrade pip
          pip install --upgrade platformio esptool

      - name: Build ClassicESP
        run: |
          ENVS="esp32 esp32-wled-esp32-ota-quinled-rgbw esp32-quinled-dig-uno-v3-wled-ota esp32-quinled-dig-uno-v3-aeplus-wled-ota esp32-quinled-dig-uno-ar-wled-ota esp32-quinled-dig-uno-aeplus-ar-wled-ota esp32s2 esp32-eth01 esp8266"
          CMD="pio run -j 2"
          for env in $ENVS; do
            CMD="$CMD -e $env"
          done
          eval "$CMD"

      - name: Upload Artifacts - ClassicESP
        uses: actions/upload-artifact@v7
        with:
          name: Hyperk-Firmware-ClassicESP
          path: release/
          if-no-files-found: error

      - name: Generate Job Summary
        run: |
          echo "**Boards:** esp32 esp32-wled-esp32-ota-quinled-rgbw esp32-quinled-dig-uno-v3-wled-ota esp32-quinled-dig-uno-v3-aeplus-wled-ota esp32-quinled-dig-uno-ar-wled-ota esp32-quinled-dig-uno-aeplus-ar-wled-ota esp32s2 esp32-eth01 esp8266" >> $GITHUB_STEP_SUMMARY

  release:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download firmware artifact
        uses: actions/download-artifact@v8
        with:
          name: Hyperk-Firmware-ClassicESP
          path: release

      - name: Create Pre-release
        uses: softprops/action-gh-release@v3
        with:
          files: release/*
          generate_release_notes: true
          draft: true
          prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
